stages:
  - build_dev # docker images
  - pre_dev # ingress
  - deploy_dev # service and deployment
  
image: alpine

variables:
  BUILD_SERVER: '1'

build_server_dev:
  stage:
    build_dev
  image: docker
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - docker login -u "$DOCKER_REGISTRY_U" -p "$DOCKER_REGISTRY_P" $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY/$DOCKER_REGISTRY_U/$CI_PROJECT_NAME/server
    - docker build --cache-from $CI_REGISTRY/$DOCKER_REGISTRY_U/$CI_PROJECT_NAME/server -t $CI_REGISTRY/$DOCKER_REGISTRY_U/$CI_PROJECT_NAME/server ./server
    - docker push $CI_REGISTRY/$DOCKER_REGISTRY_U/$CI_PROJECT_NAME/server
  rules:
    - if: $BUILD_SERVER =~ '1'
      when: always
