stages:
  - init # docker registry
  - build_dev # docker images
  - pre_dev # ingress
  - deploy_dev # service and deployment

image: alpine

variables:
  DOMAIN: $KUBE_INGRESS_BASE_DOMAIN
  BUILD_SERVER: "0"
  DEPLOY_INGRESS: "1"
  DEPLOY_SERVER: "1"

set_docker_registry:
  stage: init
  image:
    name: lachlanevenson/k8s-kubectl
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: dev
    url: $DOMAIN
  script:
    - kubectl create secret docker-registry registry-gitlab-key --docker-server=$CI_REGISTRY --docker-username=$DOCKER_REGISTRY_U --docker-password=$DOCKER_REGISTRY_P
    - . ./manifests/docker-registry-script.txt

build_server_dev:
  stage: build_dev
  image: docker
  services:
    - docker:dind
  tags:
    - docker
  before_script:
    - echo $KUBE_INGRESS_BASE_DOMAIN
    - docker login -u "$DOCKER_REGISTRY_U" -p "$DOCKER_REGISTRY_P" $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY/$DOCKER_REGISTRY_U/$CI_PROJECT_NAME/server
    - docker build --cache-from $CI_REGISTRY/$DOCKER_REGISTRY_U/$CI_PROJECT_NAME/server -t $CI_REGISTRY/$DOCKER_REGISTRY_U/$CI_PROJECT_NAME/server ./server
    - docker push $CI_REGISTRY/$DOCKER_REGISTRY_U/$CI_PROJECT_NAME/server
  rules:
    - if: $BUILD_SERVER =~ '1'
      when: always
    - if: $BUILD_SERVER !~ '1'
      when: never

deploy_ingress_dev:
  stage: pre_dev
  image:
    name: lachlanevenson/k8s-kubectl
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: dev
    url: $DOMAIN
  script:
    - cd manifests/
    - sed -i "s+DOMAIN+${DOMAIN}+g" ./ingress-server.yaml
    - kubectl apply -f ingress-server.yaml
  rules:
    - if: $DEPLOY_INGRESS =~ '1'
      when: always
    - if: $DEPLOY_INGRESS !~ '1'
      when: never

deploy_server_dev:
  stage: deploy_dev
  image:
    name: lachlanevenson/k8s-kubectl
    entrypoint: ["/bin/sh", "-c"]
  environment:
    name: dev
    url: $DOMAIN
  script:
    - cd manifests/
    - sed -i "s+CI_REGISTRY+$CI_REGISTRY+g" ./deploy-server.yaml
    - sed -i "s+DOCKER_REGISTRY_U+$DOCKER_REGISTRY_U+g" ./deploy-server.yaml
    - sed -i "s+CI_PROJECT_NAME+$CI_PROJECT_NAME+g" ./deploy-server.yaml
    - kubectl apply -f svc-server.yaml
    - kubectl apply -f deploy-server.yaml
    - kubectl get all
  rules:
    - if: $DEPLOY_SERVER =~ '1'
      when: always
    - if: $DEPLOY_SERVER !~ '1'
      when: never
