stages:
  - build
  - test
  - deploy
  
image: alpine
variables:
  cat_var: "cat"
  dog_var: "dog"  

before_script:
  - echo "This runs before the script"
after_script:
  - echo "This runs after the script"
# here we define the global keys
  
# here we will define jobs
.build_template: &build_template
  stage: build
  image: alpine:3.9
  variables:
    mouse_var: "mouse"
  script:
    - echo Job created using an anchor
  when: manual

build_a:
  <<: *build_template
    
build_b:
  <<: *build_template
  script:
    - echo Script replaced locally, variable mouse_var $mouse_var from the anchor
  when: always
    
test_a:
  stage: test
  script:
    - echo "Job test_a running in stage test"
    
.deploy_a:
  stage: deploy
  script:
    - echo "Job deploy_a running in stage deploy"