stages:
  - build_dev # docker images
  - pre_dev # ingress
  - deploy_dev # service and deployment
  
image: alpine

variables:
  BUILD_SERVER: '1'

build_server_dev:
  stage:
    build_dev
  image: docker
  services:
    - docker:dind
  tags:
    - docker
  script:
    - docker build -t server ./server
    - docker push server
  rules:
    - if: $BUILD_SERVER =~ '1'
      when: always
