apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: ingress-certificate-secret-ENV
spec:
  secretName: ingress-certificate-secret-ENV
  dnsNames:
    - DOMAIN
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - DOMAIN
  issuerRef:
    name: letsencrypt-ENV
    kind: ClusterIssuer