apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-server
  labels:
    app: server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: DOMAIN
    http:
      paths:
      - path: api/(.*)
        backend:
          serviceName: svc-server
          servicePort: 80