apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-server
  namespace: KUBE_NAMESPACE
  labels:
    app: server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-method: 'POST'
    ingress.kubernetes.io/ssl-redirect: "true"
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
      - DOMAIN
    secretName: ingress-certificate-secret-ENV
  rules:
  - host: DOMAIN
    http:
      paths:
      - path: PREFIX/api/(.*)
        backend:
          serviceName: svc-server
          servicePort: 80